spring.application.name=GestionVeterinaria

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vetcaredb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
jwt.secret=VetCareSecretKeyForJWTAuthenticationSystem2026SecureKey!!!
jwt.expiration=86400000
jwt.refreshExpiration=604800000

logging.level.org.springframework.security=WARN
logging.level.com.proyecto.GestionVeterinaria.security=DEBUG